const types = {
  SET_CURRENT: "SET_CURRENT",
  UPDATE_ALL_CHANNELS: "UPDATE_ALL_CHANNELS",
  ADD_MESSAGE_TO_CHANNEL: "ADD_MESSAGE_TO_CHANNEL",
  CHANGE_USERS_IN_CHANNELS: "CHANGE_USERS_IN_CHANNELS",
};

export default types;
